// AquaCraft Central Database Seed v1.1 - Enhanced with Hardscape, Rocks & Photo Assets

const FISH_DATABASE = [
  {
    id: "neon_tetra",
    name: "Tetra Neon",
    scientificName: "Paracheirodon innesi",
    photo: "assets/neon_tetra_art_1786638165032.jpg",
    emoji: "🐟",
    color: "#00e5ff",
    minVolume: 60,
    phMin: 6.0,
    phMax: 7.2,
    tempMin: 20,
    tempMax: 26,
    ghMin: 4,
    ghMax: 12,
    temperament: "peaceful",
    swimmingZone: "middle",
    minGroup: 8,
    maxSizeCm: 3.5,
    bioloadPts: 2,
    shrimpSafe: true,
    nanoFriendly: false,
    description: "Pesce di banco molto pacifico ed iconico con striscia blu e rossa fluo."
  },
  {
    id: "guppy",
    name: "Guppy (Poecilia)",
    scientificName: "Poecilia reticulata",
    photo: "assets/guppy_cutout_1786639413791.jpg",
    emoji: "🐠",
    color: "#f59e0b",
    minVolume: 30,
    phMin: 7.0,
    phMax: 8.2,
    tempMin: 22,
    tempMax: 28,
    ghMin: 10,
    ghMax: 25,
    temperament: "peaceful",
    swimmingZone: "top",
    minGroup: 3,
    maxSizeCm: 5.0,
    bioloadPts: 3,
    shrimpSafe: true,
    nanoFriendly: true,
    description: "Vivace e colorato con pinne a ventaglio. Predilige acque dure."
  },
  {
    id: "betta_splendens",
    name: "Betta Splendens (Combattente)",
    scientificName: "Betta splendens",
    photo: "assets/betta_fish_art_1786638177339.jpg",
    emoji: "🐟",
    color: "#f43f5e",
    minVolume: 30,
    phMin: 6.5,
    phMax: 7.5,
    tempMin: 24,
    tempMax: 29,
    ghMin: 5,
    ghMax: 15,
    temperament: "semi-aggressive",
    swimmingZone: "top",
    minGroup: 1,
    maxGroup: 1,
    maxSizeCm: 6.5,
    bioloadPts: 4,
    shrimpSafe: false,
    nanoFriendly: true,
    description: "Pesce solitario con pinne a velo. I maschi vanno tenuti da soli."
  },
  {
    id: "corydoras_sterbai",
    name: "Corydoras Sterbai",
    scientificName: "Corydoras sterbai",
    photo: "assets/guppy_cutout_1786639413791.jpg", // fallback asset
    emoji: "🐡",
    color: "#fbbf24",
    minVolume: 60,
    phMin: 6.0,
    phMax: 7.5,
    tempMin: 23,
    tempMax: 28,
    ghMin: 5,
    ghMax: 14,
    temperament: "peaceful",
    swimmingZone: "bottom",
    minGroup: 5,
    maxSizeCm: 6.0,
    bioloadPts: 4,
    shrimpSafe: true,
    nanoFriendly: false,
    description: "Pesce di fondo indispensabile per pulire il substrato dal cibo residuo."
  },
  {
    id: "scalare",
    name: "Scalare (Angelfish)",
    scientificName: "Pterophyllum scalare",
    photo: "assets/scalare_cutout_1786639446383.jpg",
    emoji: "🐠",
    color: "#a855f7",
    minVolume: 180,
    phMin: 6.0,
    phMax: 7.5,
    tempMin: 24,
    tempMax: 30,
    ghMin: 3,
    ghMax: 12,
    temperament: "semi-aggressive",
    swimmingZone: "middle",
    minGroup: 2,
    maxSizeCm: 15.0,
    bioloadPts: 15,
    shrimpSafe: false,
    nanoFriendly: false,
    predatorOfSmallFish: true,
    description: "Maestoso dei fiumi amazzonici. Diventa grande e caccia piccoli pesci."
  },
  {
    id: "ancistrus",
    name: "Ancistrus (Mangia-alghe)",
    scientificName: "Ancistrus sp.",
    photo: "assets/scalare_cutout_1786639446383.jpg",
    emoji: "🐡",
    color: "#64748b",
    minVolume: 80,
    phMin: 6.0,
    phMax: 7.5,
    tempMin: 22,
    tempMax: 28,
    ghMin: 5,
    ghMax: 18,
    temperament: "peaceful",
    swimmingZone: "bottom",
    minGroup: 1,
    maxSizeCm: 12.0,
    bioloadPts: 10,
    shrimpSafe: true,
    nanoFriendly: false,
    description: "Ottimo mangiatore di alghe con bocca a ventosa."
  },
  {
    id: "red_cherry_shrimp",
    name: "Gamberetto Red Cherry",
    scientificName: "Neocaridina davidi",
    photo: "assets/guppy_cutout_1786639413791.jpg",
    emoji: "🦐",
    color: "#ef4444",
    minVolume: 20,
    phMin: 6.5,
    phMax: 8.0,
    tempMin: 18,
    tempMax: 26,
    ghMin: 6,
    ghMax: 20,
    temperament: "peaceful",
    swimmingZone: "bottom",
    minGroup: 6,
    maxSizeCm: 2.5,
    bioloadPts: 0.5,
    shrimpSafe: true,
    nanoFriendly: true,
    description: "Piccolo spazzino rosso instancabile, ideale per nano tank."
  },
  {
    id: "rasbora_heteromorpha",
    name: "Rasbora Trigonostigma",
    scientificName: "Trigonostigma heteromorpha",
    photo: "assets/neon_tetra_art_1786638165032.jpg",
    emoji: "🐟",
    color: "#fb923c",
    minVolume: 50,
    phMin: 6.0,
    phMax: 7.2,
    tempMin: 23,
    tempMax: 28,
    ghMin: 4,
    ghMax: 12,
    temperament: "peaceful",
    swimmingZone: "middle",
    minGroup: 8,
    maxSizeCm: 4.5,
    bioloadPts: 2.5,
    shrimpSafe: true,
    nanoFriendly: false,
    description: "Pesce pacifico con caratteristica macchia nera a cuneo."
  }
];

const SUBSTRATES = [
  { id: "amber_sand", name: "Sabbia Ambrata Fine (1-2mm)", color: "#d9b382", style: "natural" },
  { id: "black_quartz", name: "Quarzo Nero Profondo (2-3mm)", color: "#2d3748", style: "dark" },
  { id: "river_gravel", name: "Ghiaia Naturale di Fiume", color: "#a0aec0", style: "pebble" },
  { id: "brown_soil", name: "Fondo Allofano Bruno Scuro", color: "#4a3728", style: "soil" }
];

const ROCKS_HARDSCAPE = [
  { id: "none", name: "Nessuno (Solo Piante)" },
  { id: "seiryu_stone", name: "Rocce Seiryu Stone (Grigie venate)", color: "#718096" },
  { id: "dragon_stone", name: "Rocce Dragon Stone (Argilla traforata)", color: "#c05621" },
  { id: "lava_rock", name: "Roccia Vulcanica Nera Porosa", color: "#1a202c" },
  { id: "driftwood", name: "Radici di Giava / Driftwood Legno", color: "#744210" }
];

const PLANT_DATABASE = [
  {
    id: "anubias_nana",
    name: "Anubias Nana",
    type: "Epifita (su legni/roccia)",
    difficulty: "Molto Facile",
    lightNeed: "Bassa",
    icon: "🌱",
    recommended: true,
    notes: "Non va interrata. Resistente a pesci fitofagi."
  },
  {
    id: "java_fern",
    name: "Felce di Giava (Microsorum)",
    type: "Epifita",
    difficulty: "Facile",
    lightNeed: "Bassa/Media",
    icon: "🌿",
    recommended: true,
    notes: "Cresce legata su rocce o radici."
  },
  {
    id: "vallisneria",
    name: "Vallisneria Spiralis",
    type: "Sfondo (Crescita Alta)",
    difficulty: "Facile",
    lightNeed: "Media",
    icon: "🎋",
    recommended: true,
    notes: "Crea una foresta di sfondo ed assorbe nitrati."
  },
  {
    id: "cryptocoryne",
    name: "Cryptocoryne Wendtii",
    type: "Medio Piano",
    difficulty: "Facile",
    lightNeed: "Bassa/Media",
    icon: "🌱",
    recommended: false,
    notes: "Radici robuste, ottima per zone d'ombra."
  },
  {
    id: "java_moss",
    name: "Muschio di Giava",
    type: "Muschio",
    difficulty: "Facile",
    lightNeed: "Bassa",
    icon: "☘️",
    recommended: false,
    notes: "Rifugio ideale per avannotti e gamberetti."
  },
  {
    id: "egeria_densa",
    name: "Egeria Densa (Elodea)",
    type: "Rapida Crescita",
    difficulty: "Molto Facile",
    lightNeed: "Media/Alta",
    icon: "🌾",
    recommended: false,
    notes: "Ossigenante rapida, combatte le alghe."
  }
];
